project:
  type: website
  render:
    - index.qmd
  output-dir: docs     # <-- must live under `project:`

website:
  title: "Fluxnet Figures"

format:
  html:
    theme: cosmo

execute:
  freeze: auto
