name: Quarto Publish

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # System libs for sf/terra/units/raster
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gdal-bin libgdal-dev libgeos-dev libproj-dev proj-bin \
            libudunits2-dev libfontconfig1-dev libxml2-dev libnetcdf-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      # Install R packages listed in DESCRIPTION
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pak
          needs: check

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        witd)
# --- Render the website WITHOUT running code (temporary) ---
      - name: Render site
        run: quarto render --no-execute


      # Upload the built site (_site) and deploy to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - 
